@WebApp_HostAddress = http://localhost:5273

### Get all animals that have arrived

GET {{WebApp_HostAddress}}/arrivals/
Accept: application/json

### Get whenever a hunt happened

GET {{WebApp_HostAddress}}/hunts/
Accept: application/json

### Get everithing that has happened to a specific animal
@animalName = Harold
GET {{WebApp_HostAddress}}/animal/{{animalName}}/actions
Accept: application/json

### Get a sumarry of animal Actions
GET {{WebApp_HostAddress}}/animal/{{animalName}}
Accept: application/json

### Get a summary of all animals
GET {{WebApp_HostAddress}}/v2/animal/
Accept: application/json

### Getting summary for a specific animal in v2
GET {{WebApp_HostAddress}}/v2/animal/{{animalName}}
Accept: application/json

### Getting summary for a specific animal in v2
GET {{WebApp_HostAddress}}/v2/animal/{{animalName}}:until?minutes=5
Accept: application/json