@WebApp_HostAddress = http://localhost:5273

### Get all animals that have arrived

GET {{WebApp_HostAddress}}/arrivals/
Accept: application/json

### Get all animals that have departed

GET {{WebApp_HostAddress}}/departures/
Accept: application/json

### Get all animals in the crown

GET {{WebApp_HostAddress}}/animals/
Accept: application/json

### Get all animals in the crown (better way)

GET {{WebApp_HostAddress}}/v2/animals/
Accept: application/json

### Who ate mussels

GET {{WebApp_HostAddress}}/meals/mussels
Accept: application/json

### Hows our food stock

GET {{WebApp_HostAddress}}/foodstock/
Accept: application/json

### Get an animal routine

@animal_name = Clifton
GET {{WebApp_HostAddress}}/animal/{{animal_name}}
Accept: application/json

### Get an animal routine up to a date

GET {{WebApp_HostAddress}}/animal/{{animal_name}}?untilDays=1
Accept: application/json